### ISSUE TITLE
Ingest folder wide search

### ISSUE THREAD

**Issue by techsavvyash** [ChakshuGautam/cQube-ingestion#116]
# Description

A new feature to search/manipulate some text throughout the CSV files present in the ingest folder.

**Comment by masterismail** [comment]
Hey @techsavvyash, I have added this feature in the File Validator project of Cqube, so that I could test it in a controlled environment with limited CSV files. It looks good to me, You can check the feature  [here](https://github.com/masterismail/File-Format-Validator). If everything looks fine, I'll add this feature here.

**Comment by masterismail** [comment]
or shall i just add the code here and make a pull request ?

**Comment by techsavvyash** [comment]
Hey @masterismail,
There is already #119 open for this, can you built and on top of that and fix that same PR?
Thanks

**Comment by masterismail** [comment]
yup, will do it !
